### ISSUE TITLE
isomiR annotations wrong

### ISSUE THREAD

**Issue by deliaBlue** [zavolanlab/mirflowz#1]
The coordinates of the isomiR annotations prepared in the _PREPARE_ workflow are (almost?) all wrong.

Example from the first six entries from file `isomirs_annotation.bed` generated by a `test/test_workflow_slurm.sh` run:

```console
1	-2	-1	MIMAT0027619	.	-	.	miRNA	.	ID=MIMAT0027619;Alias=MIMAT0027619;Name=hsa-miR-6859-3p_5p-1_3p-1;Derives_from=MI0022705
1	-2	-1	MIMAT0027618	.	-	.	miRNA	.	ID=MIMAT0027618;Alias=MIMAT0027618;Name=hsa-miR-6859-5p_5p-1_3p-1;Derives_from=MI0022705
1	-2	-1	MIMAT0005890	.	+	.	miRNA	.	ID=MIMAT0005890;Alias=MIMAT0005890;Name=hsa-miR-1302_5p-1_3p-1;Derives_from=MI0006363
1	-2	-1	MIMAT0049032	.	-	.	miRNA	.	ID=MIMAT0049032;Alias=MIMAT0049032;Name=hsa-miR-12136_5p-1_3p-1;Derives_from=MI0039740
1	-2	-1	MIMAT0004571	.	+	.	miRNA	.	ID=MIMAT0004571;Alias=MIMAT0004571;Name=hsa-miR-200b-5p_5p-1_3p-1;Derives_from=MI0000342
1	-2	-1	MIMAT0000318	.	+	.	miRNA	.	ID=MIMAT0000318;Alias=MIMAT0000318;Name=hsa-miR-200b-3p_5p-1_3p-1;Derives_from=MI0000342
```

As a consequence, the isomiR quantification in the _QUANTIFY_ workflow test fails. It was therefore disabled until this issue is resolved.

To do:
- [ ] Fix the preparation of isomiR annotations (correct coordinates)
- [ ] Reenable isomiR quantification in the tests.

**Comment by uniqueg** [comment]
I think we can close this, as we will not need this anymore with the new quantification design (see #7)
