### ISSUE TITLE
Ensure that test scripts can be successfully run from any location

### ISSUE THREAD

**Issue by deliaBlue** [zavolanlab/mirflowz#21]
Given the params on the test script to test the installation, it can only be ran from the `test/` directory.    
Refactor the test to be successfully run from any location.

**Comment by uniqueg** [comment]
For this you need to find out how, from within your test script, you can find out the path of that script - then execute all commands in the script relative to that path. Just google for that and you will find out how to do it. It's rather an advanced Bash command (compared to, say, the way you would do this in Python), but I've used it many times and it works fine.

It's generally a pattern to keep in mind for scripts - you need to always be aware where you are relative to any input/output files and relative to the current working directory.

**Comment by deliaBlue** [comment]
Could it be that it is already implemented in these lines?

```
user_dir=$PWD
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
cd $script_dir
```

**Comment by uniqueg** [comment]
Yes, that's the general pattern, I think.

**Comment by deliaBlue** [comment]
At the beginning, before the lines I posted before, there are these lines:

```
# Tear down test environment
cleanup () {
    rc=$?
    cd $user_dir
    echo "Exit status: $rc"
    rm -rf .snakemake
}
trap cleanup EXIT
```

I guess that's what you mean.

**Comment by uniqueg** [comment]
Yeah

**Comment by uniqueg** [comment]
Assuming that you have tried out that you can, indeed, successfully trigger the test runners (both for local and Slurm execution) from different locations of the file system (from a location inside the repository that is not the repository root directory and from a location _outside_ of the repository), then yes, I think this is closed.

**Comment by deliaBlue** [comment]
Yeah, sorry for not reporting it; I ran the tests from different places and all of them worked.
