### ISSUE TITLE
Extending pre-miRs overhang

### ISSUE THREAD

**Issue by deliaBlue** [zavolanlab/mirflowz#24]
The 5p and 3p pre-miR overhang relative to the canonical miRNA has to be extended up to $n$ if it is smaller than $n$.  
$n$ will be left for the user to choose and will have a default value of 10 which - by the moment will also be the maximum allowed value.  

> MIND that if any pre-miR starts at a position $< n$ or ends at a position  $> lenSeq - n$ the extension will be either as big as the difference to the  chromosome ends or there will be no extension.

**Comment by deliaBlue** [comment]
This issue must be assessed in the _prepare_ subworkflow after the rule `filter_mir_1_anno`.
There, the scrip in the [overhang assessment](https://github.com/zavolanlab/mirflowz/blob/mirna_accounting/explorations/accounting_human_mirs_overhang.ipynb) will be fused and simplified to rewrite the `gff3` file in two main steps:

1. **Compute the 5p and 3p overhang**. It is important to take strandness into account as in the `+` strand the 5p position of the mature miRNA is bigger than the pre-miR one and the 3p end position of the mature miRNA is smaller than the one from the pre-miR. On the `-` strand, the relation is inverted i.e. 3p-pre-miR coord. < 3p-mature coord. and 5p-pre-miR coord. > 5p-mature coord.
2. **Extend the sequence coordinates to reach an overhang of $n$**. $n$ will be passed as an argument read from the `config.yaml` file.  It's max value will be set 10. Again strandness must be take into account; if in the `+` strand, the 5p extension will consist on decreasing the start annotated coordinate while increasing the 3p end position. On the other hand, if the strand is the `-` one, the 3p end will be the one decreasing its end position and the 5p starting position will increase.


In addition, all the rules related to the isomiRs annotation file will be removed .

Finally, it is important to taken into account that maybe this extension leads to have the first and last entry outside the chromosome boundaries. In these cases, the extension will be done -- if possible - until the coordinate reaches these edges.

**Comment by uniqueg** [comment]
Yes, I think that sums it up pretty well :)

One thing to note perhaps: We are not currently planning to allow for different overhangs for 5p and 3p, and so the solution can be symmetrical, i.e., strandedness isn't really an issue: if we don't care about 5p and 3p, we can just deal with start and end, and in GTF and BED, the start positions will always be smaller or equal to the end positions, regardless of the strand.

If we decided to support separate params or 5p and 3p overhangs later on, we can still refactor the code to take care of strandedness.

**Comment by deliaBlue** [comment]
I spotted some  pre-miRs that the annotation file, after being filtered by transcript support level, are left without a canonical sequence - mind that this filtering has been made _a priori_ as we delete the rule because the user should provide an already filtered file, I filtered myself.  There are three option from my POV:

Do not filter the  annotation file by transcript support level and use the raw data
Do not extend the ends of that pre-miR
Do extend both ends of that pre-miR (either by the whole amount of for example half of it)

I believe that extending the pre-miR 5 bases (being 10 the default) could be the best option - not totally extended nor ignored, it's kind 50-50.

**Comment by uniqueg** [comment]
I'm a bit confused. For the miRNAs, we are using the gff3 annotation file from miRBase, not the gtf file from Ensembl. The miRBase file should never have been filtered for transcript support level.

That being said, as we discussed, filtering is on the _user's_ side now. If they provide faulty inputs, anything can happen - we can't possibly predict and address all of that. So in principle I would say, go with 1. Except that I really don't understand what you are telling me about filtering the miRNAs by support level.... ?

**Comment by deliaBlue** [comment]
Oh yeah, my bad, I switch the fiilterings... as you said, the _gff3_ files is not filtered to by transcript support level but filters out miRNA sequences ended in `_1` That's why some canonical forms are missing. A possible solution would be to compute the overhang before filtering; this way does not matter if there is an associated mature form or not

**Comment by uniqueg** [comment]
Guess that makes sense. Or we discard the orphaned pre-miRs as well.

Can you remind me again why we do the `_1` filtering? What are those `_1` miRNAs?

**Comment by deliaBlue** [comment]
The `_1` miRNAs - as well as `_2`,`"_3` - are the same mature miRNA found in different pre-miRNAs. For instance, the [pre-miR 5701](https://www.mirbase.org/textsearch.shtml?q=hsa-miR-5701) found on different regions of the chromosome 15 has its mature form IDs:

- MIMAT0022494
- MIMAT0022494_1
- MIMAT0022494_2

It makes sense to remove the ones labeled as `_1` and `_2` because they have all the same sequence but the reason behind removing only the `_1` and not also `_2` or `_3` is unknown for me (I've been struggling with this since the beginning).
This leads to two options:

1. Make the extension before the filtering and in the filtering remove all the IDs with an underscore.
2. Do not filter the IDs with an underscore and make the extension directly instead.

From my POV the best option is the second one as even if the sequence is the same, the location in the genome is not, and this gives an incomplete annotation file to be used in the intersection step.

**Comment by uniqueg** [comment]
Well, I guess if we do the fractional counting, we could leave them all in, and by adding up the counts for the different copies would/should add up to the same total that we'd get if we remove the copies and leave only one. Except that if we do not remove them, we get corresponding counts for the pre-miRs, which to me makes more sense.

So yeah, I agree, let's remove the filtering. You can create an issue for that.

Btw, please mind the order of issues in the [project board](https://github.com/orgs/zavolanlab/projects/3/views/1). This new issue you can put before #24.

I think you can start working on the issues now, I think the issues for the new counting are duly discussed. I will close #7.

**Comment by deliaBlue** [comment]
This issue was closed as it has been updated to issue #65
