### ISSUE TITLE
State an order for multiple alignments for the same read 

### ISSUE THREAD

**Issue by deliaBlue** [zavolanlab/mirflowz#30]
The script `sam_remove_duplicates_inferior_alignments_multimappers.1_5.pl` puts in a dictionary/hash  the different alignments for a single read . As these store data unordered the order may change between runs - which makes the test fail when comparing the output to the checksums. So before writing out the remaining alignments for a record, a certain order should be enforced.

**Comment by uniqueg** [comment]
Well, that was my assumption. I didn't actually check if that is what's happening. We will see. Probably it's that, or something quite like it.
