### ISSUE TITLE
Use Biocontainer images rather than lab-specific images

### ISSUE THREAD

**Issue by deliaBlue** [zavolanlab/mirflowz#5]
Currently, the pipeline uses Docker images that are stored in the lab's Docker Hub organization. Maintaining these images is tedious and will likely phase out. Replace images from `zavolab` with those from Biocontainers. This may require adding missing tools on BioConda.

**Comment by deliaBlue** [comment]
The images `r-zavolab` and `r-tidyverse`  when changed by the official ones or the biocontainers rise an error as they are missing the library `optparse`.
The same thing happens with the `python` image and the module `pysam`.
Should these be added as dependencies?

Also, the image from `oligomap` cannot be found besides the one from zavolanlab - which make sense as it has bee created here. Should I leave it as it is?

**Comment by uniqueg** [comment]
Let's see what we can do:

**Python**: I guess you can use the official Python image wherever `pysam` is not required (pretty sure not all scripts need it). For those that do need it, you can try the [`pysam` BioContainers image](https://quay.io/repository/biocontainers/pysam?tab=tags) (try to use the same `pysam` version we are currently using).

For **oligomap** and **R**, I guess you would really need to contribute the images to BioContainers yourself (ideally, for R, you'd even create one image per tool/script!). However, that's a bit of an overkill and would take too much time. Please address what you can (including Python as described above) with a PR, then create two more issues for conributing BioConductor images for (1) `oligomap` and (2) `R` and/or `tidyverse` with `optparse`. We can leave them as very low priority to fix when we have time. Link the issues here and then we can close _this_ issue when the PR is merged.

**Comment by uniqueg** [comment]
Oops, accidentally closed this. Re-opened for a minute before your PR will close it ;-)
