### ISSUE TITLE
Intersect BAM with extended miRs.

### ISSUE THREAD

**Issue by deliaBlue** [zavolanlab/mirflowz#69]
As in issue #66 , the first rule will use `bedtools intersect` with the options  `-wb` and `-F 1` but we will be using the extended miRs annotations. 

The second rule, will use the 11th column to add to the previous SAM file the name of the mature miRNA(s) an alignment overlaps the most; the name will be added as a new tag.

**Comment by deliaBlue** [comment]
This issue must also include the conversion of the BAM file into a BED file as the first step.

**Comment by uniqueg** [comment]
Can't `bedtools` handle BAM or at least SAM files?

**Comment by deliaBlue** [comment]
Closed in PR #84 .
