### ISSUE TITLE
docs: document workflow steps

### ISSUE THREAD

**Issue by deliaBlue** [zavolanlab/mirflowz#90]
Add a file for each step in the workflow a one sentence description of what it does. (See [ZARP](https://github.com/zavolanlab/zarp/blob/dev/pipeline_documentation.md) example). The "uncollapse" branch with BAM/sort/index can be skipped.

**Comment by deliaBlue** [comment]
I was wondering, should I make a section on the documentation explaining the configuration options or maybe just redirect them to the two configuration files we have a they can find there the explanation of each option?

**Comment by uniqueg** [comment]
I think that you can just link to the file and mention that detailed explanations of options are inside.

However, where it makes sense you can mention the options in the descriptions of each step, e.g., something like that: "In step X the regions annotated as pre-miRs are extended on either side, to account for isomiR species with shifted start and/or end positions. The default number of nucleotides by which these regions are extended can be configured with parameter Y.".
